# default config
spRootFolder: _catalogs/masterpage/src
dlRootFolder: ./src
gulp:
  getFields: 
    listTitle: Travel Requests
  csom: 
    siteUrl: https://jolera365.sharepoint.com/sites/senate/subsite/
    listTitle: TestList
    siteRelativeUrl: /sites/senate/subsite/
    webPartPage: Lists/custom/NewForm.aspx
# Define required parameters in local.yaml file. 
# When local config local.yaml does not exist prompts
localConfigPrompts: 
-
  message:  SharePoint Site Url
  name:     siteUrl
  default:  https://qpickit.sharepoint.com/sites/developer
-
  message:  Site relative web url
  name:     webRelativeUrl
  default:  /
-
  message:  Domain (only for On-Premises)
  name:     domain
-
  message:  User Name
  name:     username
  default:  ivan@qpickit.com
-
  message:  Password
  name:     password
  type:     password